VERSION = "0.0.6"

DISPOSITION_CODES = {
    "DISPOSED BY JUDGE": "JU",
    "DISMISSAL WITHOUT LEAVE BY DA": "VD",
    "DISMISSED BY COURT": "DC",
    "DEFERRED PROCEEDING OR DEFERRED PROSECUTION DISMISSAL": "DD",
    "WAIVER - CLERK": "WC",
}
