name: Lint and Test code

on:
  pull_request:
  schedule:
    # run once a week on early monday mornings
    - cron: '22 2 * * 1'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache docker build
        uses: actions/cache@v2
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile, requirements.txt, .pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-docker-
            ${{ runner.os }}-
      - name: Build docker images
        run: docker build -t ciprs-reader .
        run: docker run --rm -t -v "${PWD}:/usr/src/app" ciprs-reader pre-commit
      - name: Run Tests
        run: docker run --rm -t -v "${PWD}:/usr/src/app" ciprs-reader pytest
