name: Lint and Test code

on:
  pull_request:
  schedule:
    # run once a week on early monday mornings
    - cron: '22 2 * * 1'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker build
        uses: actions/cache@v2
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile', 'requirements.txt', '.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-docker-
            ${{ runner.os }}-
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          tags: ciprs-reader
          load: true
          cache-from: type=local,src=~/.cache/docker
          cache-to: type=local,dest=~/.cache/docker
      - name: Run Pre-commit
        run: echo $PWD && docker run --rm -t -v "${PWD}:/usr/src/app" ciprs-reader pre-commit
      - name: Run Tests
        run: docker run --rm -t -v "${PWD}:/usr/src/app" ciprs-reader pytest
